---

- name: Check if node exists
  command: wwsh node list {{ item.name }}
  register: wwsh_node_list
  changed_when: no
  failed_when: no
#- name: Show output
#  debug:
#    msg: "{{ wwsh_node_list }}"
- name: Add missing node
  command: wwsh -y node new {{ item.name }} --ipaddr={{ item.ip }} --hwaddr={{ item.mac }} -D {{ compute_private_nic }}
  when: wwsh_node_list.rc != 0
